name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  package:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    uses: ./.github/workflows/package.yml
    with:
      signed_release: false
